name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.1
    - name: Install dependencies
      run: |
        python3.8 -m pip install pipenv flake8
        python3.8 -m pipenv install
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python3.8 -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        python3.8 -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: python3.8 unittest
